<<: !include .base.yaml

esphome:
  name: airmonitor

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: my_mhz19

web_server:
  ota: false

i2c:
  sda: GPIO14
  scl: GPIO12

uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: my_mhz19
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
      internal: true
    update_interval: 60s
    automatic_baseline_calibration: false
  - platform: bme280
    address: 0x76
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
